//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int IDcourses { get; set; }
        public string CoursesName { get; set; }
        public System.DateTime CoursesDate { get; set; }
        public string CoursesAuthor { get; set; }
        public int CoursesCost { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
