//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editing
    {
        public int IDEditing { get; set; }
        public string EditingType { get; set; }
        public string EditingAuthor { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
