//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int IDHomeworks { get; set; }
        public string Description { get; set; }
        public string WorkAuthor { get; set; }
        public string Deadline { get; set; }
    
        public virtual Lessons Lessons { get; set; }
    }
}
