//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int IDLessons { get; set; }
        public string LessonsName { get; set; }
        public string LessonsDate { get; set; }
        public int LessonsTime { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Homework Homework { get; set; }
    }
}
