//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IDpayment { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Value { get; set; }
        public string Date { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
