//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_English
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Status { get; set; }
        public string Nickname { get; set; }
        public int PhoneNumber { get; set; }
        public string Login { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Editing Editing { get; set; }
    }
}
